# GoReleaser configuration for DailyLog MCP
# https://goreleaser.com

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # MCP Server
  - id: mcp-server
    main: ./cmd/mcp-server
    binary: dailylog
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    tags:
      - netgo

  # CLI Tool
  - id: dailyctl
    main: ./cmd/dailyctl
    binary: dailyctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    tags:
      - netgo

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - mcp-server
      - dailyctl
    files:
      - README.md
      - LICENSE
      - docs/**/*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^docs:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*enhancement[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

# Release configuration
release:
  github:
    owner: cloudygreybeard
    name: dailylog-mcp
  name_template: "{{.ProjectName}} v{{.Version}}"
  draft: false
  prerelease: auto
  mode: replace

# Homebrew tap is updated manually in the release workflow
# using SSH deploy key (HOMEBREW_DEPLOY_KEY secret)

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/cloudygreybeard/dailylog:latest"
      - "ghcr.io/cloudygreybeard/dailylog:{{ .Tag }}"
      - "ghcr.io/cloudygreybeard/dailylog:v{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

# Validation
project_name: dailylog-mcp

# Git configuration
git:
  tag_sort: -version:refname

# Environment variables
env:
  - CGO_ENABLED=0
